FactoryBot.define do
  factory :vendor_event do
    category { 'dealer' }
    # qr_token is auto-generated by before_validation callback

    association :vendor
    association :event

    trait :artist_alley do
      category { 'artist_alley' }
    end

    trait :sponsor do
      category { 'sponsor' }
    end

    trait :with_booth do
      metadata { { 'booth_number' => 'A-12', 'hall' => 'Main Hall' } }
    end
  end
end
