#!/bin/bash
# Railway Unified Utility Script
# Auto-generated by railway_setup.sh

set -e

show_help() {
    cat <<EOF
🚂 Railway Utility Commands

Usage: ./railway.sh <command>

Commands:
  logs [lines]     - Show recent deployment logs (default: 100 lines)
  tail            - Tail live logs (follows new output)
  status          - Show current deployment status
  deploy          - Deploy current branch to Railway
  vars            - Show environment variables
  services        - List all services
  open            - Open Railway dashboard in browser
  console         - Open Rails console on Railway
  db              - Open database console on Railway
  restart         - Restart the service
  help            - Show this help

Examples:
  ./railway.sh logs           # Show last 100 log lines
  ./railway.sh logs 500       # Show last 500 log lines
  ./railway.sh tail           # Follow live logs
  ./railway.sh status         # Check deployment status
  ./railway.sh deploy         # Deploy to Railway
  ./railway.sh console        # Rails console on production

EOF
}

case "${1:-help}" in
    logs)
        LINES=${2:-100}
        echo "📋 Fetching last $LINES log lines..."
        railway logs --lines $LINES
        ;;

    tail)
        echo "📋 Tailing live logs (Ctrl+C to stop)..."
        railway logs --follow
        ;;

    status)
        echo "📊 Deployment Status:"
        echo "===================="
        railway status
        echo ""
        echo "Recent deployments:"
        railway deployment list --limit 5
        ;;

    deploy)
        echo "🚀 Deploying to Railway..."
        echo "Note: Railway auto-deploys on git push. Use this for manual deployment."
        railway up
        ;;

    vars)
        echo "🔧 Environment Variables:"
        echo "========================"
        railway variables
        ;;

    services)
        echo "📦 Services:"
        echo "==========="
        railway service list
        ;;

    open)
        echo "🌐 Opening Railway dashboard..."
        railway open
        ;;

    console)
        echo "💻 Opening Rails console on Railway..."
        echo "Type 'exit' to close connection"
        railway run rails console
        ;;

    rake)
        TASK=${2:-"--tasks"}
        echo "🔧 Running rake task: $TASK"
        railway run rake $TASK
        ;;

    db)
        echo "🗄️  Opening database console on Railway..."
        echo "Type '\q' to exit"
        railway run rails dbconsole
        ;;

    restart)
        echo "🔄 Restarting service..."
        railway restart
        ;;

    help|*)
        show_help
        ;;
esac
